# 서버 포트
server:
  port: 8093

spring:
  output:
    ansi:
      enabled: always

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:templates/scdsh/

  #datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondDB?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  security:
    user:
      name: user
      password: 1234

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:

  # pasing setting
  pagination:
    write_pages: 10
    page_rows: 10


  # upload setting
  upload:
    path: upload