# 서버 포트
server:
  port: 8080

  error:
    include-stacktrace: always

spring:
  output:
    ansi:
      enabled: always

  redis:
    host: localhost
    post: 6379


  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:templates/scdsh/

  #datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondDB?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  security:
    user:
      name: user
      password: 1234

  # Naver smtp server 사용
  mail:
    host: smtp.naver.com
    port: 465
    username: devsmko@naver.com
    password: Tnals123!
    properties:
      mail:
        smtp:
          starttls:
            enable: false
          auth: true
          ssl:
            trust: smtp.naver.com
            enable: true

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:

  # pasing setting
  pagination:
    write_pages: 10
    page_rows: 10

  # upload setting
  upload:
    path: upload


# coolsms 문자 인증
coolsms:
  api:
    key: "NCSEPDRPAKJZQYG7"
    secret: "QNLN3IVMM14AP1WRFGWL9F9JDKM3ITF9"
    fromnumber: "010-7797-9285"

#logging:
#  level:
#    org.springframework: DEBUG